server:
  port: 8080

spring:
  application:
    name: restaurante

  datasource:
    url: jdbc:mysql://localhost:3306/controle_gastos?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true